Module5 task2
htmlacademy-react/356451-six-cities-5 pull request #9
Opened 2020-10-21 21:55 UTC by NikolayLemehov

2020-10-22 10:35 UTC, balesniy requested changes

2020-10-22 10:35 UTC, balesniy commented on src/components/city-filter-list/city-filter-list.jsx
> +    dispatch(ActionCreator.getSortedCityOffers());
гетеры лучше перенести в mapStateToProps, это не действия, а данные из стора

2020-10-22 10:35 UTC, balesniy commented on src/components/offer-sorting/offer-sorting.jsx
> +    this.state = {
Б16. Отсутствует мутируемый стейт в обычных компонентах: если в компоненте есть состояние, оно вынесено в HOC

2020-10-22 10:35 UTC, balesniy commented on src/components/offer-sorting/offer-sorting.jsx
> +  _onCloseMenu() {
https://up.htmlacademy.ru/react/5/criteries#d3

2020-10-22 10:35 UTC, balesniy commented on src/const.js
> +  price: {
значения перечислений нужно оформить капсом

2020-10-22 10:35 UTC, balesniy commented on src/store/action.js
> +  getSortedType: (sortType) => ({
тут точнее будет set

2020-10-22 10:35 UTC, balesniy commented on src/store/reducer.js
> +  overOfferId: offers[0].id,
при старте у нас еще нет активного предложения

2020-10-22 10:35 UTC, balesniy commented on src/store/reducer.js
> +  currentSortType: SortingType.POPULAR,
посмотри на подходы к вынесению состояния в стор - https://redux.js.org/faq/organizing-state#do-i-have-to-put-all-my-state-into-redux-should-i-ever-use-reacts-setstate и https://redux.js.org/faq/organizing-state#should-i-put-form-state-or-other-ui-state-in-my-store

2020-10-22 10:35 UTC, balesniy commented on src/store/reducer.js
> +    case ActionType.GET_FIRST_OFFER_ID:
не нашел в тз такого требования, просят подсветить при наведении

2020-10-23 07:04 UTC, NikolayLemehov commented on src/components/offer-sorting/offer-sorting.jsx
> +  _onCloseMenu() {
Исправил, залил

2020-10-23 07:18 UTC, NikolayLemehov commented on src/const.js
> +  price: {
Исправил, залил

2020-10-23 07:53 UTC, NikolayLemehov commented on src/store/reducer.js
> +    case ActionType.GET_FIRST_OFFER_ID:
Исправил, залил.

2020-10-23 07:54 UTC, NikolayLemehov commented on src/store/reducer.js
> +  overOfferId: offers[0].id,
Исправил, залил.

2020-10-23 07:55 UTC, NikolayLemehov commented on src/components/city-filter-list/city-filter-list.jsx
> +    dispatch(ActionCreator.getSortedCityOffers());
Я так понял нужно исправить get на set, как указано ниже.
Исправил, залил.

2020-10-23 22:08 UTC, merged